feat/OT108-148
alkemyTech/OT108-Client pull request #65
Opened 2021-12-24 16:34 UTC by rojasjoaquin129

![test 2](https://user-images.githubusercontent.com/54474050/147364835-024e6df1-a37b-46b7-a7b7-4b05c09be1c5.jpg)

se hizo los tests en diferentes servicios porq solo pude testear q el store dispare la accion en el login pero despues ya van todos

2021-12-25 19:50 UTC, anagon88 requested changes

2021-12-25 19:50 UTC, anagon88 commented on src/app/services/auth.service.spec.ts
> +import {
Elimina los archivos que no se usen

2021-12-25 19:50 UTC, anagon88 commented on src/app/app.component.spec.ts
> +// describe("AppComponent", () => {
No comentar codigo

2021-12-26 04:28 UTC, rojasjoaquin129 commented on src/app/app.component.spec.ts
> +// describe("AppComponent", () => {
pasa q si no comento el codigo me va a saltar el tema de q no hace todas las importaciones en cada proyecto entonces por eso comente el codigo

2021-12-30 19:49 UTC, closed without merging